---
Optimized: 
  learning_rate: 
    - float
    - 0.001
    - 0.002
  hidden_size:
    - categorical
    - [20]

Data:
    dataset: yahoo
    subset: A1
    task: anomaly
    batch_size: 64
    worker: 0
    scaler: "01"
    path: "Datasets"
    shuffle_train: False
    
Study:  
  number_of_trials: 3
  direction: minimize
  optimization_target: TrainLoss
  study_name: LAEStudyofYahooA1_xxxxxxxxxxx

Network:
  name: LinAutoEncoder
  act_function: Tanh
  input_size: 120
  
Learning:
  num_epochs: 3
  testevery: 1
  optimizer: Adam
  scheduler: StepLR
  scheduler_step: 5
  gamma: 0.8
  criterion: MSELoss