---
Optimized: 
  learning_rate: 
    - float
    - 1.0e-3
    - 1.0e-3
  hidden_size:
    - categorical
    - [20]

Data:
    dataset: yahoo
    subset: A4
    task: anomaly
    batch_size: 16
    worker: 0
    scaler: mean
    path: "Datasets"
    shuffle_train: False
    
Study:  
  number_of_trials: 1
  direction: minimize
  optimization_target: TrainLoss
  study_name: VarAEStudyofYahooA4

Network:
  act_function: Tanh
  input_size: 120
  
Learning:
  num_epochs: 100
  testevery: 5
  optimizer: Adam
  scheduler: StepLR
  scheduler_step: 8
  gamma: 0.8
  criterion: MSELoss